install:
  - "pip install -U pip"
  - "pip install -U scikit-learn scipy"
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies


# command to run tests
script: py.test